### ISSUE TITLE
Bug: Didn't get to fire first in my own battle

### ISSUE THREAD

**Issue by ideatrack** [PlayersCommittee/gemp-swccg-public#286]
I don't think I skipped the weapons segment from my side (last turn). I don't think I got to fire first with 4-LOM first although it was my battle.

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=ideatrack$0grnmvcmutn2pn6o

**Comment by EchoBaseTrooper** [comment]
When a battle is initiated, both player may have responses to that battle. This is before the weapons segment where you would use 4-LOM's permanent weapon. Both of your opponent's actions (Fallen Portal and It's A Trap!) were responses and would therefore be played before the weapons segment. (for more information, see chapter 6 of the Advanced Rulebook)

**Comment by ideatrack** [comment]
Sorry - I wasn't clear it's in the last battle where Lando was able to Axe 4-LOM before 4-Lom shot him

**Comment by EchoBaseTrooper** [comment]
Oh sorry, I was looking at a different battle. If you could put the turn number that would be helpful. The one you're talking about is turn 11, right?

It's really hard to check this in the normal GEMP interface because it's so far into the replay and would only show up for a brief moment. But checking in the new interface (which makes it easier to move around in replays) it looks like 4-LOM and Emperor Palpatine both light up in the battle before your opponent uses Lando. I think you accidentally passed your action.

![replay](https://user-images.githubusercontent.com/45436940/105561586-57281980-5cd4-11eb-9ac8-34da2ac8ecd6.PNG)

**Comment by ideatrack** [comment]
That's great - solves that. Thanks for looking into this! Especially as it was user error! :-(

New interface looks great!
