### ISSUE TITLE
DFS-1015 does not draw 2 choose 1 when with another droid starfighter

### ISSUE THREAD

**Issue by batmouse07** [PlayersCommittee/gemp-swccg-public#322]
Card should allow 2 cards to be drawn, and choose 1, when with another droid starfighter
![](https://res.starwarsccg.org/cards/TheedPalace-Dark/large/dfs1015.gif)

## Steps to reproduce:

* Replay: https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=batmouse$zqhft4ac23xz13ib
* Turn 4 battle even reverted to try and check it

**Comment by EchoBaseTrooper** [comment]
It's because your only battle destiny was "draws one battle destiny if unable to otherwise". It's like the ruling with Commander Luke Skywalker (V) and Dash In Rogue 12 where both draws count against your limit of battle destiny draws.
You weren't able to draw 2 battle destiny so the action didn't pop up.
