### ISSUE TITLE
"Are you ok" not allowing for re-deploy to Jakku

### ISSUE THREAD

**Issue by sgcstearns** [PlayersCommittee/gemp-swccg-public#346]
Expected Behavior: Forfeit Solo during my turn #2 battle at starship graveyard, get option to play "Are You Ok" and pay 1 force to redeploy to the site.  

Actual behavior: Forfeit Solo, no option to play "Are You Ok" despite 3 force active.  I was able to use the other text on it later in the game

Game link: https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=sgcstearns$qze8st3tyruq17gk

Happens in light side turn #2 battle phase

**Comment by bibfortuna25** [comment]
If you forfeited Solo on the same turn that you deployed him, then you can’t use Are You Okay to redeploy him, because uniqueness rules prohibit deploying the same unique character twice on the same turn. If you intend to use AYO, you’ll need to use it on a non-unique character, or on someone that you deployed on a previous turn. 

I discovered that the hard way months ago.

**Comment by sgcstearns** [comment]
Ah wow good catch.  I really couldn't figure out what was going on and neither could my opponent... Sorry to spam this with a GEMP bug when it was really a rules misunderstanding.
