### ISSUE TITLE
Jedi Tests buggs

### ISSUE THREAD

**Issue by Cadell81** [PlayersCommittee/gemp-swccg-public#478]
- [X] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
Jedi tests are not working correctly.  

Jedi Tests 1-4:  When attempting to complete each test, you do not get the +1 bonuse per non-generic Dagobah site on table.  

## **To Reproduce**
For Jedi tests 1-4, attempt a jedi test with Dagobah sites on table

## **Game Replay ID:**
Cadell$nbdnfrz3l6dx17ib
Cadell$dooj2kn8scok50oy
Cadell$wgeochgvrnz75mb7

## **Expected behavior**
Tests should give you +1 to training destiny per Dagobag site on table.  

## Client Platform
Desttop

**Comment by EchoBaseTrooper** [comment]
Adding 1 for each Dagobah site is optional. To do it in GEMP, you need to click on the Jedi Test each time you draw training destiny. It's not easy to see because the Jedi Test is hiding behind other cards, but it lights up after you draw destiny.

Here is an example from your first replay:
![image](https://user-images.githubusercontent.com/45436940/146422368-a61d5d9d-6bbc-4948-a679-d8503ae90231.png)
