### ISSUE TITLE
Luke in Legend not eligible to be deployed against CCT

### ISSUE THREAD

**Issue by shawnd1984** [PlayersCommittee/gemp-swccg-public#488]
- [ ] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
Luke The Last Jedi cannot be deployed in two games against the CCT Bot

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Shawnd1984$9ew092yslomvnf05
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Shawnd1984$2qfpca93si0cucql

## **To Reproduce**
3. 
4.
5. See error

**Comment by EchoBaseTrooper** [comment]
Legend says "You may not deploy Jedi while a Jedi on table." Luke couldn't be deployed because you had a Jedi on table.
The text on Be With Me that says "[Set 14] Rey ignores your [Episode VII] objective deployment restrictions" means she can deploy if you already have a Jedi on table. It doesn't allow another Jedi (Luke) to deploy if she is on table.

**Comment by shawnd1984** [comment]
My bad. Thank you for the clarification!
