### ISSUE TITLE
Solo Han not working for Arcona at Jundland Wastes  (DS)

### ISSUE THREAD

**Issue by grundius** [PlayersCommittee/gemp-swccg-public#61]
In a recent game, I had Arcona at Jundland Wastes (DS) which has LS game text that I need to have 6 ability or more to draw battle destiny. Oponent played a Storm Trooper and initiated battle. I played Solo Han to add one battle destiny. I was not prompted to draw battle destiny and the battle resolved without any damage or attrition on either side. 

I read and re-read Solo Han, but it says "If an alien is defending a battle alone at a site, add one battle destiny." Arcona is an alien, was alone, and at a site. I believe this to be a bug, or am I missing something?

Sorry that I do not have a screenshot.

**Comment by jdipaolo1** [comment]
@grundius The Dark Side text of Jundland Wastes will prevent you from drawing any battle destinies unless one of two conditions are met: You have satisfied the 6 ability requirement, or you have a card that says "draws battle destiny if unable to otherwise". "Adding a battle destiny" does not get around this.

**Comment by grundius** [comment]
@jdipaolo1 Sorry for the late reply, but thanks for the clarification.
