### ISSUE TITLE
Dejarik Rules Bug

### ISSUE THREAD

**Issue by hayesbug** [PlayersCommittee/gemp-swccg-public#624]
T2 dark should not have the option to grab houjix being played to holotable.

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Hayes$iciqkp162dfk5koj

**Comment by Gergall** [comment]
This seems related to an old bug where players used to be able to Sense/Alter a dejarik as it was being deployed to the holotable.  That bug is supposedly fixed though - https://github.com/PlayersCommittee/gemp-swccg-public/issues/230

From the AR:
Dejariks and holograms at (or deploying to) a holosite are not considered to be Interrupts and Effects (except for cards that specifically refer to them at a holosite), they are simply dejariks and holograms. For example, Alter may not cancel Molator at (or deploying to) a holosite. However, any card which specifically names a dejarik or hologram card may still affect that card (e.g., Grimtaash specifically cancels Molator).

**Comment by EchoBaseTrooper** [comment]
Fixed in recent release
