### ISSUE TITLE
Tie Defender can’t carry laser cannon battery

### ISSUE THREAD

**Issue by BadEwok** [PlayersCommittee/gemp-swccg-public#648]
The Tie Defender can sport any cannon yet I can’t deploy laser cannon battery on it. I CAN deploy it on a Sentinel landing craft which has the same wording (or at least I have been able to previously).

**Comment by EchoBaseTrooper** [comment]
This is not a bug. See the Weapons - Starship Weapons - Special Deployment section on page 9-21 of the AR which specifically uses this as an example:
> you may deploy Boosted TIE
Cannon on a TIE Defender because it deploys on a
type of starfighter, but not Laser Cannon Batteries
because that weapon only deploys on capital starships
