### ISSUE TITLE
Beggar doesn't go to Lost when opponent uses more than 1 force.

### ISSUE THREAD

**Issue by Darthjeeps** [PlayersCommittee/gemp-swccg-public#680]
Beggar doesn't go lost when opponent uses more than one Force.

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=darthjeeps$c7ytg11rwtnmjeqs

whatever.  Just go to the end of the game.

**Comment by EchoBaseTrooper** [comment]
The AR explains how Beggar works on page B-3:
>**Beggar**
This Light Side Effect remains on table and allows you to use any amount of your opponent's Dark Side Force during each of your turns. At the end of each of your turns, if you chose to use zero or 1 Dark Side Force that turn, the Beggar remains on table; if you chose to use 2 or more Dark Side Force, Beggar is lost (even if inactive). 

"However, if you use more than 1 of the opponent's Force in a turn, Beggar is lost." does not mean it is lost immediately whenever 2 or more force is used. You only check at the end of the the turn. Beggar didn't go lost during your game because it wasn't the end of the turn yet.
