### ISSUE TITLE
Luke Skywalker, Rebel Scout (non-v) - cancelling vehicle attrition immunity

### ISSUE THREAD

**Issue by bear1770** [PlayersCommittee/gemp-swccg-public#712]
- [x] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
Luke Skywalker, Rebel Scout (non-v) has "May cancel immunity to attrition of any vehicle here." in his game text.  In a recent sealed game, he used this game text to cancel immunity of a Blizzard Walker (turn 3).  In three subsequent battles with him and one without him, the walker's immunity stayed cancelled.

## **To Reproduce**
Initial battle is on turn 3.  Vehicle immunity cancelled.
More battles with Luke in turns 6, 8 and 9(DS).  Option to cancel immunity didn't come up.
Turn 9(LS) battle and walker has no immunity.

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=bear42$7vje1oj9b7dkfkm8

## **Expected behavior**
On turn 10 at least, walker should still have immunity.  Should Luke immunity cancelling work forever?

**Comment by Gergall** [comment]
Hello bear1770.  This is actually in accordance with the Advanced Rulebook and does not seem to be a bug.  From the AR section on Actions - Duration, we have the following guidelines.  Note that many cards specify how long a change lasts - these guidelines are for the cards like LSRS that don't specify a duration.

• If it happens during a battle, it lasts until the end of 
the battle OR until the affected card leaves play, 
which ever happens first.
• If it happens outside of battle, it lasts until the card 
leaves play.
• If it was caused by a weapon (even during battle), it 
lasts until the card leaves play. 

In your game, since LSRS canceled the vehicle immunity outside of battle, it lasts until the vehicle leaves play.
