### ISSUE TITLE
Jar Jar Binks action making character lost incorrectly

### ISSUE THREAD

**Issue by Mick6448** [PlayersCommittee/gemp-swccg-public#721]
During turn 5, the dark side player insisted a battle at Could City: Downtown Plaza with Darth Vader and Blizzard Scout 1 versus Princess Leia and Jar Jar Binks. Jar Jar’s text was initiated to draw destiny in an attempt to make him and Vader lost.

Dark side had no cards in reserve deck and could not draw destiny. Light side drew a location. Total would have been 0 + 2 for the light side. Dark side had no destiny + Vader’s ability of 6. 

The result was successful and both Jar Jar and Vader were lost, but should not have been.

see replay link below of game:

https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=Mick6448$dg8z7pktf5n5j68v

Light side was playing on an iPad9.7. Device for dark side is unknown.

No expected outcome - light side conceded to report bug and both players were agreeable with outcome.

**Comment by EchoBaseTrooper** [comment]
This is not a bug. The dark side player not drawing a destiny means they do not have a total to add 6 to and automatically fail.

The Failed Destiny Draws section of the AR (2023 edition), page 31:
>A player needs to successfully complete a destiny draw
in order to have a destiny total for an action (even if the
player was instructed to perform multiple destiny draws,
only one draw needs to be successfully completed to
have a destiny total). If a player has no destiny total
because they did not successfully complete any draws,
it is called a Failed Destiny Draw situation. The player
with no destiny total fails the action, meaning the action
resolves in favor of their opponent. This does not mean
that the opponent may decide how to resolve it; rather,
it means that the result is whatever is in the opponent's
immediate favor for that action.
