### ISSUE TITLE
LS Kashyyyk system not restricting destiny draw against Xizor piloting.

### ISSUE THREAD

**Issue by SuburbanJ** [PlayersCommittee/gemp-swccg-public#771]
- [x] Did you search through the list of **open issues** _first_ to ensure that there is not already an report for this issue?

## **Describe the bug**
Battle occurred at LS Kashyyyk. DS had Jabba's space cruiser with Xizor piloting (ability 5 total), Proxima, Ponda Baba, and an outer rim scout aboard, with IG-88 in IG-2000 there as well. Battle occurred, DS should have 0 destinies, but drew one anyways.

## **To Reproduce**
1. Xizor piloting a ship in battle at Kashyyyk with <6 ability total.
2. See error

## **Game Replay ID:**
https://gemp.starwarsccg.org/gemp-swccg/game.html?replayId=SuburbanJ$hqk9qeqlhafcy3yl
Turn 6 is when the event occurred.

## **Expected behavior**
DS should not be allowed to draw any battle destiny due to not satisfying Kashyyyk's ability requirement.

### **Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Unsure

## **Additional context**
It's possible that it's caused by either IG-88 in IG-2000 or Lady Proxima, but I think the most likely cause is Xizor's text triggering in a space battle when it should only work at sites.

**Comment by EchoBaseTrooper** [comment]
This is not a bug. Outer Rim Scout was piloting, not Prince Xizor. Outer Rim Scout draws battle destiny if unable to otherwise when piloting an [Independent] starship.

Relevant part of game log:
ElDuderino moves •Prince Xizor from pilot capacity slot to passenger capacity slot of •Jabba's Space Cruiser (V)
ElDuderino deploys Outer Rim Scout from •Den Of Thieves on •Jabba's Space Cruiser (V) as pilot

**Comment by SuburbanJ** [comment]
We both totally didn’t realize he had done that! Thank you for looking into
it!
